StudentProject/AdminSchool/Models/ErrorViewModel.cs
using System;

namespace AdminSchool.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StudentProject/AdminSchool/Controllers/HomeController.cs
using AdminSchool.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AdminSchool.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StudentProject/AdminSchool/Controllers/LoginController.cs
using DataAccess.Concrete;
using EntityLayer;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Policy;
using System.Threading.Tasks;

namespace AdminSchool.Controllers
{

    public class LoginController : Controller
    {
        Context c = new Context();
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GirisYap(string returnUrl)
        {
            TempData["returnUrl"] = returnUrl;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> GirisYap(User user)
        {
            var information = c.Users.FirstOrDefault(x => x.userName == user.userName && x.password == user.password);
            if (information != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,user.userName),
                    
                };

                var identity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(principal);

                if (TempData["returnUrl"] != null)
                {
                    if (Url.IsLocalUrl(TempData["returnUrl"].ToString()))
                    {
                        return Redirect(TempData["returnUrl"].ToString());
                    }
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

            }
            return View();
        }
    }
    }

StudentProject/AdminSchool/Controllers/StudentController.cs
using AdminSchool.Models;
using BusinessLayer.Abstract;
using BusinessLayer.ValidationRules;
using DataAccess.Concrete;
using EntityLayer;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace AdminSchool.Controllers
{
    public class StudentController : Controller
    {
        private readonly Context c = new Context();
        private readonly IStudentService studentService;
        Student st;
        public StudentController(IStudentService studentService)
        {
            this.studentService = studentService;
        }

   
        public IActionResult Index()
        {
            var result = studentService.ListAllStudents();
            return View(result);
        }


        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Add(Student student)
        {
            StudentValidator studentValidator = new StudentValidator();
            ValidationResult results = studentValidator.Validate(student);
            if (results.IsValid)
            {
                studentService.AddStudent(student);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        [HttpGet]

        public IActionResult Update(int id)
        {
            var result = c.Students.FirstOrDefault(x => x.studentId == id);
            return View(result);
        }
        [HttpPost]
        public IActionResult Update(Student student)
        {
            StudentValidator studentValidator = new StudentValidator();
            ValidationResult results = studentValidator.Validate(student);
            if (results.IsValid)
            {
                studentService.UpdateStudent(student);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var result = c.Students.FirstOrDefault(x => x.studentId == id);
            studentService.DeleteStudent(result);
            return RedirectToAction("Index");
        }
   

    }
    }

StudentProject/AdminSchool/Controllers/TeacherController.cs
using BusinessLayer.Abstract;
using BusinessLayer.ValidationRules;
using DataAccess.Concrete;
using EntityLayer;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using FluentValidation.Results;
using ValidationResult = FluentValidation.Results.ValidationResult;

namespace AdminSchool.Controllers
{
    public class TeacherController : Controller
    {
        private readonly Context c = new Context();
        private readonly ITeacherService teacherservice;
        Teacher teach;



        public TeacherController(ITeacherService teacherservice)
        {
            this.teacherservice = teacherservice;
        }
        public IActionResult Index()
        {

            var result = teacherservice.ListAllTeachers();
            return View(result);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        
        public IActionResult Add(Teacher teacher)
        {
            TeacherValidator teacherValidator = new TeacherValidator();
            ValidationResult results = teacherValidator.Validate(teacher);
            if (results.IsValid)
            {
                teacherservice.AddTeacher(teacher);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        [HttpGet]
        public IActionResult Update()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Update(Teacher teacher)
        {
            TeacherValidator teacherValidator = new TeacherValidator();
            ValidationResult results = teacherValidator.Validate(teacher);
            if (results.IsValid)
            {
                teacherservice.UpdateTeacher(teacher);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(Teacher teacher)
        {
            teacherservice.DeleteTeacher(teacher);
            return RedirectToAction("Index");
        }

    }
}

StudentProject/AdminSchool/Views/Login/GirisYap.cshtml
@{
    Layout=null;
}

@using EntityLayer
@model EntityLayer.User

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Login Page</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="../../assets/css/style.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="../../assets/images/favicon.ico" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
          <div class="row flex-grow">
            <div class="col-lg-4 mx-auto">
              <div class="auth-form-light text-left p-5">
                <div class="brand-logo">
                  <h2>LOGIN</h2>
                            </div>
                        <form asp-action="GirisYap" asp-controller="Login" method="post" class="pt-3"> 
                        <div class="mb-3">
                       <label for="userName" class="form-label">Username</label>
                       <input type="text" class="form-control" name="userName">
                      </div>
                     <div class="mb-3">
                     <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" name="password">
                   </div>
                   <button type="submit" class="btn btn-primary">LOGIN</button>
                 </form>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="../../assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="../../assets/js/off-canvas.js"></script>
    <script src="../../assets/js/hoverable-collapse.js"></script>
    <script src="../../assets/js/misc.js"></script>
    <!-- endinject -->
  </body>
</html>

StudentProject/AdminSchool/Views/Student/Add.cshtml
            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        <div class="col-12 grid-margin">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title">
                                        Student Information
                                    </h4>                                  
                                    <form asp-action="Add" asp-controller="Student" method="post">
                                        <div class="mb-3 mt-5">
                                            <label for="studentName" class="form-label">Student Name</label>
                                            <input type="text" class="form-control" name="studentName">

                                        </div>
                                        <div class="mb-3">
                                            <label for="studentSurname" class="form-label">Student Surname</label>
                                            <input type="text" class="form-control" name="studentSurname">
                                        </div>
                                        <button type="submit" class="btn btn-primary">ADD STUDENT</button>
                                    </form>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        </div>

StudentProject/AdminSchool/Views/Student/Index.cshtml
@using EntityLayer
@model List<Student>

        <!-- partial -->
        <div class="main-panel">
          <div class="content-wrapper">
                    <div class="row">
                        <div class="col-12 grid-margin">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title">
                                        STUDENT LIST PAGE
                                    </h4>
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>                                                       
                                                        <a href="/Student/Add" class="btn  btn-success text-white">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                                                                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                                                            </svg>
                                                        </a>
                                                       
                                                    </th>
                                                    <th>Student Id</th>
                                                </tr>
                                            </thead>
                                            @{
                                                foreach (var item in Model)
                                                {


                                                    <tbody>
                                                        <tr>
                                                            <td>
                                                                <img src="~/assets/images/faces/face1.jpg" class="me-2" alt="image">@item.studentName @item.studentSurname
                                                            </td>
                                                            <td>@item.studentId</td>
                                                            <td>
                                                                <a asp-controller="Student" asp-action="Delete" asp-route-id="@item.studentId" class="btn  btn-danger text-white ml-2">
                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                                                                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                                                                    </svg>
                                                                </a>
                                                                <a asp-controller="Student" asp-action="Update" asp-route-id="@item.studentId" class="btn  btn-warning text-white ml-2">
                                                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                                                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                                                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                                                                    </svg>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                }
                                            }
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      

StudentProject/AdminSchool/Views/Student/Update.cshtml
@using EntityLayer
@model EntityLayer.Student


            <!-- partial -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        <div class="col-12 grid-margin">
                            <div class="card">
                                <div class="card-body">
                                    <h4 class="card-title">
                                        STUDENT UPDATE PAGE
                                    </h4>
                                    <form asp-action="Update" asp-controller="Student" method="post">
                                        <div style="display:none"class="mb-3">
                                            <label for="studentId" class="form-label">Student Id</label>
                                            <input readonly asp-for="studentId" type="text" class="form-control">
                                        </div>
                                        <div class="mb-3">
                                            <label for="studentName" class="form-label">Student Name</label>
                                            <input  asp-for="studentName" type="text" class="form-control">
                                        </div>
                                        <div class="mb-3">
                                            <label for="studentSurname" class="form-label">Student Surname</label>
                                            <input type="text" class="form-control" asp-for="studentSurname">
                                        </div>
                                        <button type="submit" class="btn btn-primary">UPDATE STUDENT</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- content-wrapper ends -->
                <!-- partial:partials/_footer.html -->
                <!-- partial -->
            </div>
            <!-- main-panel ends -->
        

StudentProject/AdminSchool/Views/Teacher/Add.cshtml
<div class="container">


    <form asp-action="Add" asp-controller="Teacher" method="post">
        <div class="mb-3">
            <label for="teacherName" class="form-label">Teacher Name</label>
            <input type="text" class="form-control" name="teacherName">

        </div>
        <div class="mb-3">
            <label for="teacherSurname" class="form-label">Student Surname</label>
            <input type="text" class="form-control" name="teacherSurname">
        </div>
        <button type="submit" class="btn btn-primary">ADD TEACHER</button>
    </form>




</div>

StudentProject/AdminSchool/Views/Teacher/Index.cshtml
@{
    Layout = null;
}
@using EntityLayer
@model List<Teacher>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<div class="container">
    <div class="p-5 w-50 mx-3">
    </div>
    <br />


    <div class="card">
        <h5 class="card-header bg-secondary text-white">Student List</h5>
        <div class="card-body bg-white">
            <h5 class="card-title">
                <a href="/Teacher/Add" class="btn  btn-success text-white">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                        <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                    </svg>
                </a>
                <a href="/Teacher/Delete" class="btn  btn-danger text-white">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x" viewBox="0 0 16 16">
                        <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                    </svg>
                </a>
                <a href="/Teacher/Update" class="btn  btn-warning text-white">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                    </svg>
                </a>
            </h5>

            <table class="table table-bordered bg-white">

                <thead>
                    <tr>
                        <th>Teacher Id</th>
                        <th>Teacher Name</th>
                        <th>Teacher Surname</th>
                    </tr>
                </thead>

                @foreach (var item in Model)

                {
                    <tbody>
                        <tr>
                            <td>@item.teacherId</td>
                            <td>@item.teacherName</td>
                            <td>@item.teacherSurname</td>
                        </tr>
                    </tbody>

                }



            </table>

        </div>
    </div>

</div>

StudentProject/AdminSchool/Views/Teacher/Update.cshtml
<div class="container">


    <form asp-action="Update" asp-controller="Teacher" method="post">
        <div class="mb-3">
            <label for="teacherId" class="form-label">Teacher Id</label>
            <input type="text" class="form-control" name="teacherId">
        </div>
        <div class="mb-3">
            <label for="teacherName" class="form-label">Teacher Name</label>
            <input type="text" class="form-control" name="teacherName">
        </div>
        <div class="mb-3">
            <label for="teacherSurname" class="form-label">Teacher Surname</label>
            <input type="text" class="form-control" name="teacherSurname">
        </div>
        <button type="submit" class="btn btn-primary">UPDATE TEACHER</button>
    </form>




</div>